baseurl = "https://omega-coder.me"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "en"
title = "0m3g4K0d3r's Security Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "omega-coder"
googleAnalytics = "UA-126655681-1"
publishdir = "omega-coder.github.io"

[Params]
  homeTitle = "Security Blog"
  subtitle = "Just Another Security Oriented Blog."
  logo = "img/profile_pic.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "omega_coder"
  website = "https://omega-coder.me"
  email = "admin@omega-coder.me"
  facebook = "yacinewebdz"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "omega-coder"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "yacine_cherief"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  instagram = "omega_coder"
  youtube = "channel/UCJ84GVWJlcEjLVckwgtH58g" # or channel/channelname
  #soundcloud = "username"
  spotify = "omega_coder"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

